export const FETCH_FORECAST_WEATHER_DATA_PENDING = "FETCH_FORECAST_WEATHER_DATA_PENDING";
export const FETCH_FORECAST_WEATHER_DATA_SUCCESS = "FETCH_FORECAST_WEATHER_DATA_SUCCESS";
export const FETCH_FORECAST_WEATHER_DATA_ERROR = "FETCH_FORECAST_WEATHER_DATA_ERROR";
export const CLEAR_FORECAST_WEATHER_DATA = "CLEAR_FORECAST_WEATHER_DATA";