export const FETCH_WEATHER_DATA_PENDING = "FETCH_WEATHER_DATA_PENDING";
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS";
export const FETCH_WEATHER_DATA_ERROR = "FETCH_WEATHER_DATA_ERROR";